Fliplet/fliplet-widget-app-submission

interface.html, js/formValidation.js, js/interface.js, widget.json
This PR essentially adds all the necessary fields for data capture as well as some validation code
=> Chore adding platforms

interface.html, js/interface.js
Update radio buttons to repopulate
=> Updates Marketing URL to re populate

interface.html, js/interface.js
- Added Version Number
- Fixed issue with Splash Screen
- Error message if icon isn't 1024x1024
- Validation for numbers with area code
=> Added Version Number

css/interface.css, interface.html, js/interface.js, vendor/validator.js
Reverts Fliplet/fliplet-widget-app-submission#13
=> Revert "Changes to UI and how users enter their Apple Dev Account details"

css/interface.css, interface.html, js/interface.js, js/interface.templates.js, js/templates/thumbs.interface.hbs, widget.json
Made a new branch to be able to merge the changes from feat/screenshot-details without conflicts from this PR https://github.com/Fliplet/fliplet-widget-app-submission/pull/16
=> Added changes from feat/screenshot-details

js/interface.js
set default credential id to ensure that credential is set on build request
=> set default credential id

interface.html, js/interface.js
Changed property name as it creates confusion with other fastlane options
=> Changed property name

interface.html, js/interface.js
- Added support to open the File Manager in an overlay in the Screenshots section
=> Open file manager

js/interface.js
Ref. https://github.com/Fliplet/fliplet-studio/issues/2394
=> Ensures user is uploading new screenshots for validation to apply

interface.html
Untested, please confirm this is mandatory and renders correctly on add/edit and changes are saved correctly.
@jgustafsson24 cc
=> Added default reviewer notes, made field mandatory

js/interface.js
fixes https://github.com/Fliplet/fliplet-widget-app-submission/pull/48
=> keep default value on review notes

interface.html
Also removes autocomplete for all fields.
=> Adds warning message to review notes

js/interface.js
Ref. https://github.com/Fliplet/fliplet-studio/issues/2787
=> Adds missing '=' character in query parameter

css/interface.css, interface.html
=> Tweaks how the indented containers are spaced out

interface.html
As per Apple announcement https://developer.apple.com/news/?id=08312018a ...
=> Adds warning for Privacy Policy to be required from Oct 3rd

js/interface.js
Clear dropdown options when retrieving team list from Apple
=> Fixes issue where dropdown options are duplicated when logging in multiple times

interface.html, js/interface.js
Ref. https://github.com/Fliplet/fliplet-studio/issues/3299
=> Fixes an issue where users couldn't carry out further actions after selecting a team

js/interface.js
Ref. https://github.com/Fliplet/fliplet-studio/issues/3228
=> Fixes an issue where app stores cannot be changed

js/interface.js
ref https://github.com/Fliplet/fliplet-studio/issues/3512
=> check for undefined var

interface.html
ref https://github.com/Fliplet/fliplet-app-wrapping/pull/162
=> copy for when debug link is not available

js/interface.js
Ref.
- https://github.com/Fliplet/fliplet-studio/issues/3860
- https://github.com/Fliplet/fliplet-studio/issues/3861
- https://github.com/Fliplet/fliplet-studio/issues/3862
- https://github.com/Fliplet/fliplet-studio/issues/3863
=> Fixes issues where AAB interface isn't loaded correctly in Safari

js/interface.js
Requires https://github.com/Fliplet/fliplet-api/pull/3181
=> Hides 2FA prompts when errors are encountered

js/interface.js
ref https://github.com/Fliplet/fliplet-studio/issues/3984
=> don't verify credentials when setting the app password

js/interface.js
Ref. https://github.com/Fliplet/fliplet-studio/issues/4116
=> Code tidy up

js/interface.js
Ref. https://github.com/Fliplet/fliplet-studio/issues/4262
Requires https://github.com/Fliplet/fliplet-api/pull/3332 and https://github.com/Fliplet/fliplet-api/pull/3333
=> Wait for socket connection before login or getting teams

js/interface.js
Ref. https://github.com/Fliplet/fliplet-studio/issues/4638
=> Ensure all keywords are saved

js/interface.js
Ref. https://github.com/Fliplet/fliplet-studio/issues/4666
=> Allow all non-enterprise accounts to submit app store apps

interface.html
=> added warning for certificates duration

interface.html, js/interface.js
@squallstar @tonytlwu 
**Fixed behavior:**
When demo user information is provided, a demo password is required.
ref Fliplet/fliplet-studio#4703
=> Add validation to demo pass when demo user isn't empty

css/interface.css, interface.html, js/interface.js
Fliplet/fliplet-studio#4963
Added App analytics tab, added logic to display analytics status as enabled/disabled. 
New look:
=> Added 'App analytics' tab

interface.html
Fliplet/fliplet-studio#4963
Added "(Optional)" word to App analytics tab
=> Added "(Optional)" word to App analytics tab

css/interface.css, interface.html, js/interface.js
Fliplet/fliplet-studio#4668
Limited max length on the bundle ID input to 155 chars. Added bootstrap tooltip. Bundle ID name will be hidden if it is too long.
=> Bundle ID name will be hidden if it is too long, tooltip will appear to display full name

js/interface.js
Most of the code has been copied from similar code above and tweaked.
ref https://github.com/Fliplet/fliplet-studio/issues/5031
=> fixes issue for cloning unsigned credentials

js/interface.js
ref https://github.com/Fliplet/fliplet-studio/issues/5031
=> fixes for unsigned builds being marked as enterprise

js/interface.js
https://github.com/Fliplet/fliplet-studio/issues/5097
Added file extension check
=> Added file extension check

interface.html, js/interface.js
https://github.com/Fliplet/fliplet-studio/issues/5098
Checking if firebase was connected
=> Checking if firebase was connected

js/interface.js
ref https://github.com/Fliplet/fliplet-studio/issues/5442
=> Improves 2FA experience for returning clients

interface.html
https://github.com/Fliplet/fliplet-studio/issues/5531
Added links to articles provided by Brett.
=> Help links now lead to correct articles about analytics

css/interface.css, interface.html
https://github.com/Fliplet/fliplet-studio/issues/5490
Changed text and centered it vertically.
New look
=> Corrected app icon name description 

interface.html, js/interface.js
ref https://github.com/Fliplet/fliplet-studio/issues/4679
=> allow certificate to be downloaded once generated

js/interface.js
Requires https://github.com/Fliplet/fliplet-studio/pull/6331
=> [Feature] Track app launch events via Studio

interface.html
https://github.com/Fliplet/fliplet-studio/issues/5752
Updated text according to Johanna's comment.
@upplabs-alex-levchenko @YaroslavOvdii
=> Changed push notifications text

interface.html
Ref. https://github.com/Fliplet/fliplet-studio/issues/6602
=> [Maintenance] Updates Kayako URLs to new WordPress site

interface.html
Ref. https://weboo.atlassian.net/browse/ID-471
=> ID-471 [Maintenance] Adds information on app privacy question requirements

js/interface.js
OD-128 https://weboo.atlassian.net/browse/OD-128
- Added submission update while the method `clone` is failed
http://somup.com/crnelmo8zo
@upplabs-alex-levchenko @ivandevupp, @YaroslavOvdii 
Related from feature and comment - https://weboo.atlassian.net/browse/OD-128?focusedCommentId=11563
=> OD-128 [Fix] All information in AAB has disappeared

interface.html
Ref. https://weboo.atlassian.net/browse/ID-840
=> ID-840 [Feat] Adds admin labels

interface.html
Ref. https://weboo.atlassian.net/browse/ID-1039
=> ID-1039 [Fix] Error displaying interface

js/interface.js
Ref. https://github.com/Fliplet/fliplet-studio/issues/6940 https://weboo.atlassian.net/browse/ID-1346
Follows https://github.com/Fliplet/fliplet-widget-app-submission/pull/128
=> ID-1346 [Feat] Include all save buttons when disabling form

interface.html, js/interface.templates.js
@sofiiakvasnevska @inna-bieshulia
OD-129 https://weboo.atlassian.net/browse/OD-129
**Problem:** Incorrect text in help block and no validation for Release Notes.
**Solution:** Added correct text and set up validation for the Release Notes input.
https://storyxpress.co/video/kt01g17ldrryoxu62
=> OD-129 [FIX] Validate Release notes for iOS AAB

css/interface.css, interface.html, js/interface.js
- Added limits based on app plan
an
=> [Feat] Added limits based on app plan

js/interface.js
- Fire event when opening billing section
=> [Maintenance] Fire event when opening billing section

js/interface.js
https://weboo.atlassian.net/browse/GD-384
- Fixes an issue that prevented users to save their progress and would open the billing section instead.
=> GD-384 [Fix] Allow to save progress

interface.html, js/interface.js, vendor/validator.js
@romanyosyfiv
OD-598 https://weboo.atlassian.net/browse/OD-598
Added app-specific password validation. The user will not be able to submit the form until they enter the correct password
https://storyxpress.co/video/kvi9zl7vf4snypux4
=> OD-598 [Feature] Added app-specific password validation

interface.html, js/interface.js, vendor/validator.js
@romanyosyfiv
OD-595 https://weboo.atlassian.net/browse/OD-595
Added copyright information validation. The user will not be able to submit the form if copyright information contains url, doesn't contains  current year and if doesn't contains some text.
https://storyxpress.co/video/kvmbzfbdcivqrl6nc
=> OD-595 [Feature] Added copyright information validation

interface.html, js/interface.js
@romanyosyfiv
OD-600 https://weboo.atlassian.net/browse/OD-600
Added Bundle ID validation. The user will not be able to submit the form if the Bundle ID is in the wrong format.
https://storyxpress.co/video/kwaeejbvgwxs24ur8
=> OD-600 [Feature] Added Bundle ID validation

interface.html, js/interface.js, vendor/validator.js
@romanyosyfiv
OD-596 https://weboo.atlassian.net/browse/OD-596
Added app version number validation. The user will not be able to submit the form if the version number is in the wrong format or is less than a pre-existing version number.
https://storyxpress.co/video/kvuqi9hn52bid7iwn
=> OD-596 [Feature] Added app version number validation

interface.html
@romanyosyfiv
OD-703 https://weboo.atlassian.net/browse/OD-703
Changed text in Price section of AAB
=> OD-703 [Fix] Changed text in Price section of AAB

css/interface.css, interface.html, js/interface.js
@romanyosyfiv
OD-599 https://weboo.atlassian.net/browse/OD-599
Added app icon,  splash screen, scrennshots validation. The user will not be able to submit the form if the app icon,  splash screen, scrennshots have not been added.
www.awesomescreenshot.com/video/7143091?key=60f620a903dd0076f9fa777efad2b6bb
=> OD-599 [Feature] Added app icon,  splash screen, scrennshots validation

interface.html
@romanyosyfiv @inna-bieshulia
OD-755 https://weboo.atlassian.net/browse/OD-755
The link has been replaced with a new one.
=> OD-755 [Fix] Fix broken link

js/interface.js
Ref. https://weboo.atlassian.net/browse/ID-2119
=> ID-2119 [Fix] Allow the same version number be used until it's submitted for build

interface.html, js/interface.js
@romanyosyfiv @inna-bieshulia 
OD-446 https://weboo.atlassian.net/browse/OD-446
Added authentication key validation. The user will not be able to save the form if the version number is in the wrong format.
www.awesomescreenshot.com/video/8165361?key=f07f9d80a98153ab95ff87f2e7cd799a
=> OD-446 [Feature] Added authentication key validation for push notification settings

js/interface.js
@romanyosyfiv @inna-bieshulia
OD-764 https://weboo.atlassian.net/browse/OD-764
www.awesomescreenshot.com/video/8479192?key=cb97a2bc93493f9abe79930f61b7dbb6
=> OD-764 [Feature] Deactivating the Apple AAB Save button if the Authentication Key is not in the right format.

interface.html, js/interface.js
**Product areas affected**
App->Publish->Apple App Store->App Store->App submission details
**What does this PR do?**
Notes field should be required when submitting an app to app store
[JIRA ticket](https://weboo.atlassian.net/browse/XOR-320)
**Result**
**Checklist**
-None
**Testing instructions**
-None
**Deployment instructions**
-None
**Author concerns**
-None
=> XOR-320 [FEAT] Ensure notes field should be required when submitting an app to app store

interface.html
Studio->Publish->Apple App Store->Push Notifications
Removed broken link from Apple AAB interface
[JIRA ticket](https://weboo.atlassian.net/browse/XOR-546)
https://user-images.githubusercontent.com/108272606/193022151-a4502b63-a0ef-40a6-893c-a512c8991235.mp4
None
None
None
=> XOR-546 [FIX] Remove a broken link from the Apple AAB interface

js/interface.js
App submission ->  APK/IPK files rendering URL
This PR will ensure that the submission's APK/IPK files do not have a token on rendering 
[XOR-574](https://weboo.atlassian.net/browse/XOR-574)
Add any relevant sample input/output, screenshots or screen recordings.
https://user-images.githubusercontent.com/101858104/194862192-f1163696-2dd2-4797-ab03-42f45691927a.mp4
=> XOR-574 [FEAT] Ensure submission's APK/IPK files do not have a token on rendering 

interface.html
Ref. https://weboo.atlassian.net/browse/ID-2923
=> ID-2923 [Fix] Validate character length for release and review notes

js/interface.js
- Check if error response is handled
https://weboo.atlassian.net/browse/GD-450
https://github.com/Fliplet/fliplet-studio/pull/7543
=> GD-450 [Feat] Check if error response is handled

interface.html, js/interface.js
Ref. https://weboo.atlassian.net/browse/ID-3598
=> ID-3598 [Feat] Add version number to build summary

interface.html, js/interface.js
https://weboo.atlassian.net/browse/ID-4358
=> feat(ID-4358): showing success instead of fail message when build completed with errors

interface.html, js/interface.js
fliplet-widget-app-submission
Ensures user isn't seeing Fliplet Admin settings
[PS-422](https://weboo.atlassian.net/browse/PS-422)
[PS-422]: https://weboo.atlassian.net/browse/PS-422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PS-422/[FIX]: Ensures user isn't seeing Fliplet Admin settings

interface.html, js/interface.js
Reverts Fliplet/fliplet-widget-app-submission#176 due to QA fail.
=> Revert "PS-422/[FIX]: Ensures user isn't seeing Fliplet Admin settings"

interface.html
fliplet-widget-app-submission
Ensures user isn't seeing Fliplet Admin settings
[PS-422](https://weboo.atlassian.net/browse/PS-422)
[PS-422]: https://weboo.atlassian.net/browse/PS-422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PS-422-[FIX]: Ensures user isn't seeing Fliplet Admin settings

interface.html
Reverts Fliplet/fliplet-widget-app-submission#178 due to QA fail.
=> Revert "PS-422-[FIX]: Ensures user isn't seeing Fliplet Admin settings"

interface.html
=> Add changes to test on staging

js/interface.js
Fliplet-widget-app-submission
Ensures user isn't seeing Fliplet Admin settings
[PS-422](https://weboo.atlassian.net/browse/PS-422)
[PS-422]: https://weboo.atlassian.net/browse/PS-422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix/PS-422: Ensures user isn't seeing Fliplet Admin settings

interface.html
Fliplet  Widget  App Submission
Ensures publishing support documents takes you to the right  place
[PS-233](https://weboo.atlassian.net/browse/PS-233)
[PS-233]: https://weboo.atlassian.net/browse/PS-233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PS-233 [FIX]: Ensures publishing support documents takes you to the right  place
