js/interface.js
We now fetch the first completed submission that has the correct
certification values (in store) or published on Enterprise.
=> In the cases that we don't have the credentials object, p12 fetch fixed

js/interface.js
Adds app name restriction when loading data programmatically
=> Ensures app names are restricted to 30 characters when loaded from app settings

interface.html
Ref. https://github.com/Fliplet/fliplet-studio/issues/3261
> Two-Factor Authentication is not currently supported. Apple does not allow disabling Two-Factor Authentication. We recommend creating an account that without enabling Two-Factor Authentication that can be used with Fliplet
**EDIT** Updated to
> If your account has Two-Factor Authentication enabled and you can't turn it off, please ask your IT to create a secondary account without 2FA to be used with Fliplet.
=> Updates note on disabling 2FA

interface.html
Ref. https://github.com/Fliplet/fliplet-studio/issues/3757
=> Removes duplication of the word "technical" in AAB interface

js/interface.js
ref https://github.com/Fliplet/fliplet-studio/issues/3829
- don't rely on `fl-credentials` since they're not set for manual submissions
- avoid doing unwanted validation
- better displayed dates (HH:mm format)
=> fixes for enterprise submissions with manual login details

css/interface.css, interface.html, js/interface.js, js/interface.templates.js, widget.json
Teams will no longer be automatically loaded when you open the AAB UI. This is because 2FA might be required, and if it's automated process, users will be unexpectedly asked to enter 2FA code.
They don't need to enter login details again, though. We've simply added a **Load teams** button, which will load the teams on demand -- and might require 2FA verification using the UI above if necessary.
=> Add support for 2FA code in Apple logins when requested

js/interface.js
Ref. https://github.com/Fliplet/fliplet-studio/issues/3261
2FA requests are sent from Fliplet's server, which wouldn't be the same as the user's browser location.
To avoid confusion, the prompt copy is updated to, "Apple has sent a verification code to your devices from **(location based on user authentication token prefix)**"
=> Copy update for 2FA prompt

css/interface.css, interface.html, js/interface.js
App-specific password is saved in organisation credentials as `crendential.appPassword`.
=> Adds UI for entering app-specific password

css/interface.css, interface.html, js/interface.js
- Add support for 2FA within the AAB UI, without needing to interact with `Fliplet.Modal` for entering 2FA
- Supports more possible states provided by Apple 2FA, as outlined in https://github.com/Fliplet/fliplet-api/pull/3193
- Make it easier for AAB login form states to manage
=> Refactored to support 2FA within the AAB UI

css/interface.css, interface.html, js/interface.js, js/interface.templates.js, js/templates/no-thumb.interface.hbs, js/templates/thumb-containers.interface.hbs, js/templates/thumbs.interface.hbs
Requires https://github.com/Fliplet/fliplet-studio/pull/4096
Adds support for new screenshot size requirements as per upcoming changes from Apple. This adds support for the 1242 x 2688 screenshot for iPhone XS Max.
It also updates the validation to be more specific about which screenshots are missing.
=> Adds support for new screenshot size requirements

js/interface.js
Most of the time the screenshots are generated/uploaded in the correct size, so we're allowing this anomaly.
=> Re-introducing a bug to allow app submission

interface.html, js/interface.js
ref https://github.com/Fliplet/fliplet-studio/issues/4383
=> validate version number

js/interface.js
Ref. https://github.com/Fliplet/fliplet-studio/issues/4601
The function callers are already running validation checks, so it's safe to remove the validation.
=> Avoid app-specific passwords from being reset

interface.html
=> app-password is now required; copy change

js/interface.js
https://github.com/Fliplet/fliplet-studio/issues/3755
Created a save function witch is saving data on change icon or splash screen.
Slightly altered saving functions so that they return a promise.
=> Saving form information when user go to another modal

interface.html, js/interface.js
=> Interface to upload Firebase file

css/interface.css, interface.html, js/interface.js
@tonytlwu @squallstar
Fliplet/fliplet-studio#2832
Now when the app is successfully requested, Modal window is fired. After confirming it, the page gets scrolled to 'building app' section.
Removed green text 'Your request was sent successfully!' under Request App button and all CSS related to it.
Edge
Chrome
Behavior: "smooth" attribute that gives smooth scrolling works only on Chrome, Firefox, Opera. Other browsers (IE, Edge) will scroll page instantly.
=> When app is successfully requested, Modal window opens and page scrolls to 'building app' section

js/interface.js
https://github.com/Fliplet/fliplet-studio/issues/5189
When we press the `Save progress` button we will create firebase credentials if the file was added.
Pressing the `Save progress` button.
Creating submission without pressing the `Save progress` button.
Please look at the comment I've left in the code.
=> When we press the Save progress button we will create firebase credentials if the file was added.

js/interface.js
https://github.com/Fliplet/fliplet-studio/issues/4041
Users now cannot upload files with wrong extension
=> Users now cannot upload files with wrong extension

js/interface.js
https://github.com/Fliplet/fliplet-studio/issues/2149
Tabs will be scrolled to the top of the content when they open
=> Tabs will be scrolled to the top of the content when they open

js/interface.js
https://github.com/Fliplet/fliplet-studio/issues/6045
Removed clone credential error on submission create 
https://share.getcloudapp.com/rRu65WXJ
I was able to test it properly only on the unsigned app.
=> Removed clone credential error on submission create 

interface.html
https://github.com/Fliplet/fliplet-studio/issues/5949
User will see an error message if he tries to input white-spaces in the icon name
https://share.getcloudapp.com/DOu8b5vj
You may test regex that we use [here](https://www.regextester.com/?fam=115635).
@upplabs-alex-levchenko @MaksymShokin
=> User will see an error message if he tries to input white-spaces in icon name

interface.html, js/interface.js
Ref. https://weboo.atlassian.net/browse/ID-2119
Fixes the following problems:
1. Version number allows non-numeric characters
Caused by https://github.com/Fliplet/fliplet-widget-google-submission/pull/61
=> ID-2119 [Fix] Restrict to numbers in semantic versioning

js/interface.js
Ref. https://weboo.atlassian.net/browse/ID-2900
Reverses what https://github.com/Fliplet/fliplet-widget-app-submission/pull/45 did, which picks the first successful app build instead of the latest.
=> ID-2900 [Fix] Use result from the latest completed submission instead of the first

css/interface.css, interface.html, js/apnValidation.js, widget.json
https://weboo.atlassian.net/browse/ID-4326
https://github.com/Fliplet/fliplet-widget-app-submission/assets/144125903/4cc2d1b1-82aa-47a4-a266-65c78cdd60e7
=> feat(ID-4326): added apns config validation button
